version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-tftest
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            make test

workflows:
  version: 2

  test:
    jobs:
      - test
